### ISSUE TITLE
Focus problem still occurs 

### ISSUE THREAD

**Issue by C0D10X** [davidkgriggs/PlayniteModernUI#34] opened 2021-11-25 18:46 UTC
Issue #25 still occurs.

When pressing "a" for going into details page, the focus is not on play button. You have to press up or down so you can press the play button. Also moving up from the description it loses focus again.

**Comment by davidkgriggs** [comment] 2021-11-25 19:35
Can you send a video of this. I cannot reproduce it. Mine focuses on the play button and goes down smoothly and then back to the play button smoothly.

**Comment by C0D10X** [comment] 2021-11-25 19:53
Sended a video on Discord PM

**Comment by davidkgriggs** [comment] 2021-11-29 10:21
Fixed in v1.2.3

**Closed by davidkgriggs** 2021-11-29 10:21 UTC
